# Generated by Django 4.1 on 2024-04-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_remove_fotografia_legenda_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Humanos', 'Humanos'), ('SERES MÁGICOS', 'Seres Mágicos'), ('SERES DAS TREVAS', 'Seres das Trevas'), ('DIVINDADES', 'Divindades')], default='', max_length=100),
        ),
    ]
